### ISSUE TITLE
not able to install fbprophet due to c++ compiler issue

### ISSUE THREAD

**Issue by rajnishrajput12** [facebook/prophet#1357]
not able to install fbprophet. it is throwing
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

although i have these versions of Visuall C++ installed already:-

Microsoft Visual C++ 2015 Redistributable(X64)-14.0.23206
Microsoft Visual C++ 2013 Redistributable(X64)-14.0.23206
Microsoft Visual C++ 2013 Redistributable(X64)-14.0.23206
Microsoft Visual C++ 2015 Redistributable(X64)-14.0.23206

my details:-
Python:- 3.7.3
conda- version:- 4.6.11
pip version:- 19.3.1
anaconda3:- 2019.03

**Comment by bletham** [comment]
In Anaconda, are you installing with conda forge? Anaconda has its own build environment where this usually all "just works".

**Comment by rajnishrajput12** [comment]
I am using pip install in anaconda prompt..after coming to step installing setup.py it shows Error of c++ compiler 14 is required

**Comment by bletham** [comment]
Try
```
conda install gcc
```
and then after that, try installing with conda forge instead of pip
```
conda install -c conda-forge fbprophet
```

**Comment by Alemaudit** [comment]
I have two conda.yml files to create a conda environment with `pystan` and `fbprophet`, which work on Windows 10 and Debian GNU/Linux 9 stretch.

Would it be helpful?

**Comment by bletham** [comment]
@Alemaudit that could be useful also in the future, please paste it if you can!

**Comment by rajnishrajput12** [comment]
Yup that correct so many people are struggling because of this issue

**Comment by Alemaudit** [comment]
There you go! The dependencies `libpython` and `m2w64-toolchain` are needed for Win only.

```yml
name: prophet-env
channels:
  - conda-forge
  - msys2
  - plotly
dependencies:
  - python=3.7.4
  - libpython
  - m2w64-toolchain
  - numpy
  - cython
  - pandas
  - matplotlib
  - pystan
  - scikit-learn
  - statsmodels
  - fbprophet
```
