### ISSUE TITLE
Holidays are not being fitted anymore

### ISSUE THREAD

**Issue by gentnm** [facebook/prophet#1607]
Hi,

I had setup fbprophet for use in a JupyterLab environment on Win10 2 weeks ago and everything was going fine. I had to do the setup again this week and now the holidays are not being recognized anymore. I can reproduce this on another machine as well. It seems there was a release of some new package version in a dependency that seems to break this, but I can't figure out which.

This is the environment.yaml I use to create the conda environment:
```yaml
name: fbprophet-jupyter
channels:
    - conda-forge
    - msys2
    - defaults
dependencies:
    - python=3.7
    - cython
    - jupyterlab
    - nodejs
    - cx_oracle
    - sqlalchemy
    - plotly
    - matplotlib==3.2.2
    - fbprophet
```
matplotlib is set to 3.2.2 since the 3.3.0 release also slowed down plotting in fbprophet a lot. But that's another issue ;)

Any pointers or help are welcome and thank you for the awesome tool 👍 

Best regards
Michael
